### ISSUE TITLE
No specifier called Slice2SeriesSpecifier

### ISSUE THREAD

**Issue by dchandan** [NCAR-CISL-ASAP/PyReshaper#1]
The test scripts (under source/pyreshaper/test) expect to be able to import the symbol ``Slice2SeriesSpecifier`` from ``pyreshaper.specification``, but no such symbol is defined in the module ``pyreshaper.specification``. I think the test scripts might be outdated.

**Comment by kmpaul** [comment]
Please use the last tag. Not the master branch. Currently, I cannot
guarantee that the master is stable. Sorry!

-- Kevin

On Sunday, July 12, 2015, Deepak Chandan <notifications@github.com> wrote:

> The test scripts expect to be able to import the symbol
> Slice2SeriesSpecifier from pyreshaper.specification, but no such symbol
> is defined in the module pyreshaper.specification. I think the test
> scripts might be outdated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NCAR-CISL-ASAP/PyReshaper/issues/1>.
>


-- 
____________________________________________________________
Kevin Paul
The National Center for Atmospheric Research
Computational and Information Systems Laboratory
(303) 497-2441

**Comment by kmpaul** [comment]
Actually, I guess before I wrote that, I should have asked if you cloned
the master or a tag or got the package from PyPI...?

-- Kevin

On Monday, July 13, 2015, Kevin Paul <kpaul@ucar.edu> wrote:

> Please use the last tag. Not the master branch. Currently, I cannot
> guarantee that the master is stable. Sorry!
>
> -- Kevin
>
> On Sunday, July 12, 2015, Deepak Chandan <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> The test scripts expect to be able to import the symbol
>> Slice2SeriesSpecifier from pyreshaper.specification, but no such symbol
>> is defined in the module pyreshaper.specification. I think the test
>> scripts might be outdated.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NCAR-CISL-ASAP/PyReshaper/issues/1>.
>>
>
>
> --
> ____________________________________________________________
> Kevin Paul
> The National Center for Atmospheric Research
> Computational and Information Systems Laboratory
> (303) 497-2441
>
>

-- 
____________________________________________________________
Kevin Paul
The National Center for Atmospheric Research
Computational and Information Systems Laboratory
(303) 497-2441

**Comment by dchandan** [comment]
I cloned the master branch

**Comment by kmpaul** [comment]
Ok.  Sorry about that.  I have been the only developer on this for about a
year, now, and we just recently switched to Github from a private svn
server.  I developed some bad habits.

Thanks for the pull request.  I will review it today and merge it, if I
have time.  Hopefully today.

Thanks, btw!

On Mon, Jul 13, 2015 at 7:35 AM, Deepak Chandan <notifications@github.com>
wrote:

> I cloned the master branch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NCAR-CISL-ASAP/PyReshaper/issues/1#issuecomment-120928806>
> .
>



-- 
____________________________________________________________
Kevin Paul
The National Center for Atmospheric Research
Computational and Information Systems Laboratory
(303) 497-2441

**Comment by dchandan** [comment]
Thanks Paul!
