### ISSUE TITLE
Nio installed but setup still fails

### ISSUE THREAD

**Issue by dchandan** [NCAR-CISL-ASAP/PyReshaper#2]
I am finding that in the case of installing on two separate systems, one mac, one HPC system, that the setup script complains about not being able to find Nio. In both cases I do have Nio installed. By removing the requirement for Nio in ``setup.py`` I am able to get the installation to finish, but i haven't tests the results. Do you know why the check for Nio is failing?

**Comment by dchandan** [comment]
So looks like the script fails because according to [this link](https://pythonhosted.org/setuptools/setuptools.html#declaring-dependencies) the dependencies must be for PyPI project names, and presently PyNIO 1.4 is not on PyPI.

**Comment by kmpaul** [comment]
You are correct. I believe that is stemming partly from differences between
distutils and setup tools, and it may not completely understand those
differences yet. I am hoping to have a new release soon.

-- Kevin

On Sunday, July 12, 2015, Deepak Chandan <notifications@github.com> wrote:

> So looks like the script fails because according to this link
> <https://pythonhosted.org/setuptools/setuptools.html#declaring-dependencies>
> the dependencies must be for PyPI project names, and presently PyNIO 1.4 is
> not on PyPI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NCAR-CISL-ASAP/PyReshaper/issues/2#issuecomment-120755981>
> .
>


-- 
____________________________________________________________
Kevin Paul
The National Center for Atmospheric Research
Computational and Information Systems Laboratory
(303) 497-2441

**Comment by dchandan** [comment]
I sent a pull request for checking whether Nio is installed which should work in all cases regardless of where Nio is installed from.

**Comment by kmpaul** [comment]
Yes, I noticed.  Thanks!  That's a great idea.

On Mon, Jul 13, 2015 at 7:36 AM, Deepak Chandan <notifications@github.com>
wrote:

> I sent a pull request for checking whether Nio is installed which should
> work in all cases regardless of where Nio is installed from.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NCAR-CISL-ASAP/PyReshaper/issues/2#issuecomment-120929477>
> .
>



-- 
____________________________________________________________
Kevin Paul
The National Center for Atmospheric Research
Computational and Information Systems Laboratory
(303) 497-2441

**Comment by kmpaul** [comment]
I just merged your pull request.

Thanks, again!

(Btw, the bug with the Slice2SeriesSpecifier names was fixed in a branch
but hasn't been merged in, yet.  I don't mind fixing it in the trunk, and I
like your fix for the Nio version, so I'm merging it.)

On Mon, Jul 13, 2015 at 7:42 AM, Kevin Paul <kpaul@ucar.edu> wrote:

> Yes, I noticed.  Thanks!  That's a great idea.
>
> On Mon, Jul 13, 2015 at 7:36 AM, Deepak Chandan <notifications@github.com>
> wrote:
>
>> I sent a pull request for checking whether Nio is installed which should
>> work in all cases regardless of where Nio is installed from.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NCAR-CISL-ASAP/PyReshaper/issues/2#issuecomment-120929477>
>> .
>>
>
>
>
> --
> ____________________________________________________________
> Kevin Paul
> The National Center for Atmospheric Research
> Computational and Information Systems Laboratory
> (303) 497-2441
>



-- 
____________________________________________________________
Kevin Paul
The National Center for Atmospheric Research
Computational and Information Systems Laboratory
(303) 497-2441

**Comment by kmpaul** [comment]
Deepak,

Incidentally, the PyNIO team is working toward the release of a new version
of PyNIO and PyNGL.  There have been some delays with this release, but one
part of their plan is to put PyNIO and PyNGL on PyPI, which will
(hopefully) allow me to go back to the previous way of checking the Nio
install.

-- Kevin

On Mon, Jul 13, 2015 at 8:39 AM, Deepak Chandan <notifications@github.com>
wrote:

> Closed #2 <https://github.com/NCAR-CISL-ASAP/PyReshaper/issues/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NCAR-CISL-ASAP/PyReshaper/issues/2#event-354419779>.
>



-- 
____________________________________________________________
Kevin Paul
The National Center for Atmospheric Research
Computational and Information Systems Laboratory
(303) 497-2441
